server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
           routes:
             - id: authentication_service
               uri: lb://AUTHENTICATION-SERVICE
               predicates:
                 - Path=/auth/**
               filters:
                 - name: RequestRateLimiter
                   args:
                     key-resolver: '#{@ipKeyResolver}' 
                     redis-rate-limiter.replenishRate: 5 
                     redis-rate-limiter.burstCapacity: 10 
                     redis-rate-limiter.requestedTokens: 1 
             - id: user_service_route
               uri: lb://USER-SERVICE 
               predicates:
                 - Path=/api/users/**
                 - Method=GET,POST
               filters:
                 - StripPrefix=1 
                 - AuthorizationHeader
             - id: product_service_route
               uri: lb://PRODUCT-SERVICE 
               predicates:
                 - Path=/api/products/**
                 - Header=X-Version, v2 
               filters:
                 - AddRequestHeader=X-Forwarded-By, ApiGateway
                 - AuthorizationHeader
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: yourVerySecretKeyThatIsAtLeast32BytesLongAndShouldBeSecurelyManaged
  expiration: 3600000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

gateway:
  public-paths: /auth/**